### ISSUE TITLE
App crashes in video play

### ISSUE THREAD

**Issue by zh-wowtv** [googlesamples/leanback-showcase#13]
Error message:

> java.lang.NoClassDefFoundError: android.media.session.MediaSession

when I'm trying to run the app in android 4.4. I think it's because MediaSession is not supported in 4.4. Am I right? What is the best practice if I want to support MediaSession when I'm running in Android 5.0 and above and without MediaSession running in Android 4.2 and above.

Thanks.

**Comment by keyvanamiri** [comment]
As you suggested, MediaSession was added in API 21, and that's why you are receiving this crash. We have updated the app and will soon be releasing a new version. In this version, we made the app compatible for API level 17 and above. One of the changes related to your issue is we are now using MediaSessionCompat to make it backward compatible.

**Comment by zh-wowtv** [comment]
Great. Thanks.
