### ISSUE TITLE
setSearchAffordanceColors not working on BrowseFragment

### ISSUE THREAD

**Issue by Mokto** [googlesamples/leanback-showcase#20]
Hi,

This is what I tried :

on CustomTitleView.java

```java

private final SearchOrbView mSearchOrbView;
....


private final TitleViewAdapter mTitleViewAdapter = new TitleViewAdapter() {
       ....
        @Override
        public void setSearchAffordanceColors(SearchOrbView.Colors colors) {
            mSearchOrbView.setOrbColors(colors);
        }
}

public BrowseTitleView(Context context, AttributeSet attrs, int defStyle) {
        ....
        mSearchOrbView = (SearchOrbView) root.findViewById(R.id.search_orb);
}
```

But when I call `setSearchAffordanceColors` from my BrowseFragment, color is not set.

See related : #18 

Thanks !

**Comment by Mokto** [comment]
BTW I also tried to change Theme.Example.LeanbackBrowse theme :

```xml
        <item name="defaultSearchColor">@color/accent</item>
        <item name="defaultSearchBrightColor">@color/accent</item>
        <item name="defaultSearchIconColor">@color/icons</item>
```

Still not working (it works for icon color). Thanks !

**Comment by tracyliu1** [comment]
I also tried to set the style of SearchOrbView
`<android.support.v17.leanback.widget.SearchOrbView
        android:id="@+id/search_orb"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_vertical|start"
        android:layout_marginTop="8dp"
        android:paddingStart="48dp"
        style="@style/custom_searchOrb"
        android:transitionGroup="true"
        android:visibility="visible"/>`

it didn't work too.
Even in the showcase demo.,the searchIconcolor  of  SearchOrbView is White, and the searchcolor  of SearchOrbView is Green.but in my AndroidTV app. sometimes it worked, sometimes it's only a searchIcon without any color.

` <style name="Theme.Example.LeanbackBrowse" parent="Theme.Leanback.Browse">

        <item name="android:windowBackground">@color/card_examples_background</item>
        <item name="defaultBrandColor">@color/fastlane_background</item>
        <item name="defaultSearchColor">@color/search_color</item>
        <item name="defaultSearchIconColor">@color/search_icon_color</item>
        <item name="defaultSearchBrightColor">@color/search_bright_color</item></style>`

the style, I tried several times, only defaultSearchIconColor,

I have compared the Androidmanifest.xml the Javacode at the Fragment. still could't find the bug.
It's  really confused me!
hope your guys can understand what I say.


Thanks!!!

**Comment by dakegu** [comment]
The theme will not work unless your custom layout xml file reference the theme attribute.

If you want go through java code path, doing BrowseFragment.setSearchAffordanceColors(), I am not sure it's the TitleViewAdapter.setSearchAffordanceColors() not called or it's called but no effect? Your description is not cleared so I have to guess. The easiest way to track is to set breakpoint and debug it from android studio. You have source code of leanback library, the only places it calls the TitleViewHelper.setSearchAffordanceColors() is in BrandedFragment (parent class of BrowseFragment):

1. BrandedFragment.setSearchAffordanceColors()
2. BrandedFragment.setTitleView(), it passes color to adapter right after query Adapter from the title view

**Comment by aglt** [comment]
I had the same problem as tracyliu1 trying to get the search button to display the correct colors. It seems like this CustomTitleView in the demo for the PageAndListRowFragment is not even working correctly. It is **not** displaying the color for the SearchOrbView that is configured in the themes.xml. And because it is not picking them up, it is displaying some fallback color for the search (green). I did not investigate much, but it has something to do with the naming of the SearchOrbView instance in the custom_titleview.xml  (android:id="@+id/search_orb") because SearchOrbView itself has a view with that name, if you rename it in the custom_titleview.xml, then it will pick up the colors in the themes.xml but it will display really strangely.

Please try to repreduse by:

1. Go to custom_titleview.xml and change the name of the SearchOrbView android:id="@+id/search_orb"
2. Change the name in CustomTitleView. (mSearchOrbView = root.findViewById(R.id....)) 

![before](https://user-images.githubusercontent.com/4155016/38781652-0c00fa5a-40d8-11e8-9178-a99fe958f253.PNG)
![after](https://user-images.githubusercontent.com/4155016/38781651-0be65916-40d8-11e8-9970-89a9512f37e6.png)
![theme](https://user-images.githubusercontent.com/4155016/38781653-0c1adca4-40d8-11e8-8e64-64e88277f065.PNG)

**Comment by aglt** [comment]
Changing the the properties of the SearchOrbView as described in in issue [#55](https://github.com/googlesamples/leanback-showcase/issues/55) fixed the issue for me.

Note: In my case, when the id of the SearchOrbView was 'search_orb', then the colors from the theme would not apply to the SearchOrbView. Changing the id, made the colors work, and adding the padding/cliptopadding/clipchildren fixed the shadow issues.

```
    <android.support.v17.leanback.widget.SearchOrbView
        android:id="@+id/search_orb_view"
        ...
        android:clipChildren="false"
        android:clipToPadding="false"
        android:padding="16dp" />
```

**Comment by anurag7141** [comment]
[https://stackoverflow.com/a/53276425/3260396](url)
Hope this helps and solve your problem.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location and updates are happening there (check README for more information).

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
